### ISSUE TITLE
Bajar archive zip con datos de natalidad del INEGI de un año entre 2017 y 2022

### ISSUE THREAD

**Issue by alx3416** [Rubensotelo03/Ciencia-24#1]
Realizar función para su uso como dataframe. dicha función ebe estar en imports.py

Considerar un archive similar a main.py para el análisis de los datos del INEGI

[datos natalidad INEGI](https://drive.google.com/drive/folders/1IAaK-9jHEwSu3QaF3rfgnqszZWJOkhKR?usp=drive_link)

**Comment by Rubensotelo03** [comment]
close #7

**Comment by Rubensotelo03** [comment]
close #7
