### ISSUE TITLE
Visualización de datos

### ISSUE THREAD

**Issue by alx3416** [Rubensotelo03/Ciencia-24#2]
Con los datos de INEGI generar un heatmap con 3 variables que sean de interés

El análisis debe ser para un estado o region, usar la función drop de pandas para descartar filas

**Comment by Rubensotelo03** [comment]
close #7

**Comment by Rubensotelo03** [comment]
close #7 Se hizo el heatmap con ploty, es interactivo y muestra la edad del padre, la edad de la madre y el número de total de hijos por un rango de edad.

**Comment by Rubensotelo03** [comment]
close https://github.com/Rubensotelo03/Ciencia-24/pull/7 Se hizo el heatmap con ploty, es interactivo y muestra la edad del padre, la edad de la madre y el número de total de hijos por un rango de edad. es del estado de jalisco. Se utilizaron los datos de conjunto_de_datos_natalidad_2021_csv

<img width="494" alt="Captura de pantalla 2024-09-04 212451" src="https://github.com/user-attachments/assets/a5ecaf63-0119-4d63-8b7f-7ce66c1481cd">
